version: "3.0"
services:
  frontend:
    image: aimie-angular
    build:
      context: aimie-angular
    ports:
      - 443:443
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
    healthcheck:
      test: ["CMD-SHELL", "curl --fail localhost:80/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./aimie-angular/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/pki/tls/certs/apache-selfsigned.crt:/etc/pki/tls/certs/certificate.crt
      - /etc/pki/tls/private/apache-selfsigned.key:/etc/pki/tls/private/private.key
    networks:
      - aimie

networks:
  aimie:
    external: true
