version: "3.0"
services:
  frontend:
    image: aimie-angular
    build:
      context: aimie-angular
    ports:
      - 443:443
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
    healthcheck:
      test: ["CMD-SHELL", "curl --fail localhost:443/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./aimie-angular/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/pki/tls/certs/apache-selfsigned.crt:/etc/pki/tls/certs/certificate.crt:ro
      - /etc/pki/tls/private/apache-selfsigned.key:/etc/pki/tls/private/private.key:ro
    networks:
      - aimie
  backend:
    image: aimie-go
    build:
      context: aimie-go
    ports:
      - 8080:8080
    environment:
      - GO_ENV=STAGING
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
    healthcheck:
      test:
        ["CMD-SHELL", "curl --fail localhost:8080/api/v1/heartbeat || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./internal/config/config.staging.yaml:/app/internal/config/config.staging.yaml
    networks:
      - aimie

networks:
  aimie:
    external: true
